# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_a', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(choices=[('asfa', 'asfa'), ('asfasfa', 'asfasf')], max_length=50)),
                ('second_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Pupils',
        ),
    ]
