# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 03:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_a', '0004_auto_20170621_0615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pupil',
            old_name='first_name',
            new_name='pupil',
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='second_name',
        ),
    ]
