# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 03:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_a', '0005_auto_20170621_0616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='pupil',
            field=models.CharField(choices=[('Рахмонов Хайём', 'Рахмонов Хайём'), ('РЛфырало Оофыола', 'РЛфырало Оофыола')], max_length=50, verbose_name='Ученик'),
        ),
    ]
