# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_a', '0008_auto_20170621_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pupil',
            name='data_add',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
    ]
